### ISSUE TITLE
Multi-line Javascript

### ISSUE THREAD

**Issue by iadj** [botpress/botpress-rivescript#2]
Is there a way to execute multi line Javascript on receiving a message with Rivescript, or should all javascript be compressed down to one line first?

**Comment by slvnperron** [comment]
Currently Javascript should be a single line. The way you can execute multi-line is by defining function in your code:

```js
// index.js

module.exports = function(bp) {
   // your usual bot code [...]
  // inject your function in bp
  bp.rsHandleMessage = (event, rs) => { 
    // multi-line javascript
  }
}
```

And in rivescript: `JS: bp.rsHandleMessage(event, rs)`

Does that make sense? We wanted to prevent people from adding logic in the rivescript files, so that all Javascript is at the same place.

Thanks

**Comment by Okazari** [comment]
i love the fact that i have to register my functions into `bp` and that i have a full access to `bp` within rivescript. You should give some hint in the doc tho.

**Comment by Okazari** [comment]
Will do when i finished migrating my messenger/rivescript bot to botpress ;)

**Comment by Okazari** [comment]
Since #5 is merged, this issue can be closed :)
